name: ds-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.2.9
  - flake8=3.8.4
  - black=20.8b1
  - python=3.10
  - pandas=2.0.1
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.11.2
  - scikit-learn=1.2.2
  - statsmodels=0.14.0
  - plotly=5.14.1
  - streamlit
  - openpyxl
  - requests
  - fastapi
  - uvicorn
  - pip
  - pip:
      - mlflow==2.4.1
      - sentence-transformers